--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/David-pm-pl/ChestKits
build-by-default: true
branches:
- stable
- pm5
projects:
  ChestKits:
    path: ""
    icon: "assets/images/icon.png"
    libs:
    - src: JinodkDevTeam/FormAPI/libFormAPI
      version: ^1.4.0-alpha
    lint:
      phpstan: false
...
